config/routes.rb
Rails.application.routes.draw do
  resources :share_model_buckets
  resources :share_models
  resources :salaries
  resources :spendings
  get 'welcome/index'

  resources :associates
  resources :incomes

  root 'welcome#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/share_model.rb
class ShareModel < ApplicationRecord
  has_many :share_model_buckets
  MAX_INT = 2 ** 62

  def compute_contribution(amount)
    # We sort from the highest bucket to the smallest
    buckets = self.share_model_buckets.sort { |a, b| b.lower_bound  <=> a.lower_bound }

    result = buckets.inject({contribution: 0, upper_bound: MAX_INT}) do |result, bucket|
      if amount > bucket.lower_bound
        to_split = [result[:upper_bound], amount].min - bucket.lower_bound
        contribution = result[:contribution] + to_split * bucket.rate

        {contribution: contribution, upper_bound: bucket.lower_bound}
      else
        result
      end
    end

    result[:contribution]
  end
end

app/controllers/share_models_controller.rb
class ShareModelsController < ApplicationController
  before_action :set_share_model, only: [:show, :edit, :update, :destroy]

  # GET /share_models
  def index
    @share_models = ShareModel.all
  end

  # GET /share_models/1
  def show
  end

  # GET /share_models/new
  def new
    @share_model = ShareModel.new
  end

  # GET /share_models/1/edit
  def edit
  end

  # POST /share_models
  def create
    @share_model = ShareModel.new(share_model_params)

    if @share_model.save
      redirect_to @share_model, notice: 'Modèle de répartition créé.'
    else
      render :new
    end
  end

  # PATCH/PUT /share_models/1
  def update
    if @share_model.update(share_model_params)
      redirect_to @share_model, notice: 'Modèle de répartition mis à jour.'
    else
      render :edit
    end
  end

  # DELETE /share_models/1
  def destroy
    @share_model.destroy
      redirect_to share_models_url, notice: 'Modèle de répartion supprimé.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_share_model
      @share_model = ShareModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def share_model_params
      params.require(:share_model).permit(:label)
    end
end

app/helpers/share_models_helper.rb
module ShareModelsHelper
end

app/views/share_models/_form.html.erb
<%= form_with(model: share_model, local: true) do |form| %>
  <% if share_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(share_model.errors.count, "error") %> prohibited this share_model from being saved:</h2>

      <ul>
      <% share_model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nom %>
    <%= form.text_field :label, id: :share_model_label %>
  </div>
  <div class="actions">
    <%= form.submit :Enregistrer%>
  </div>
<% end %>

app/views/share_models/edit.html.erb
<h1>Modification d’un modèle de répartition</h1>

<%= render 'form', share_model: @share_model %>

<h2> Tranches de contribution</h2>
<div>
  <table id=buckets>
    <thead>
        <th> À partir de </th>
        <th> mutualiser </th>
    </thead>
    <tbody>
        <%= render @share_model.share_model_buckets%>
    </tbody>
  </table>

  <%= form_for @share_model.share_model_buckets.new do |f| %>
    <%= f.hidden_field :share_model_id, value: @share_model.id %> 
    À partir de <%= f.number_field :lower_bound, min: 0%>,
    mutualiser <%= f.number_field :rate, in: -100..100%>%.
    <%= f.submit 'Ajouter une tranche'%>
  <% end %>
</div>

<%= link_to 'Voir', @share_model %> |
<%= link_to 'Retour', share_models_path %>

app/views/share_models/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Modèles de répartition</h1>

<table>
  <thead>
    <tr>
      <th>Étiquette</th>
      <th>Tranches</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @share_models.each do |share_model| %>
      <tr>
        <td><%= share_model.label %></td>
        <td><ul>
        <% share_model.share_model_buckets.each do |bucket| %>
          <li><%= bucket.lower_bound_euros %> € : <%= "%.2f" % (bucket.rate * 100) %> %</li>
        <% end %>
        </ul></td>
        <td><%= link_to 'Voir', share_model %></td>
        <td><%= link_to 'Éditer', edit_share_model_path(share_model) %></td>
        <td><%= link_to 'Supprimer', share_model, method: :delete, data: { confirm: 'Êtes-vous sûr ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouveau modèle de répartition', new_share_model_path %>

app/views/share_models/new.html.erb
<h1>Nouveau modèle de contribution</h1>

<%= render 'form', share_model: @share_model %>

<%= link_to 'Retour', share_models_path %>

app/views/share_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Label:</strong>
  <%= @share_model.label %>
</p>
<table>
  <thead>
      <th> À partir de </th>
      <th> mutualiser </th>
  </thead>
  <tbody>
      <%= render @share_model.share_model_buckets%>
  </tbody>
</table>

<%= link_to 'Éditer', edit_share_model_path(@share_model) %> |
<%= link_to 'Retour', share_models_path %>