config/routes.rb
Rails.application.routes.draw do
  resources :share_model_buckets
  resources :share_models
  resources :salaries
  resources :spendings
  get 'welcome/index'

  resources :associates
  resources :incomes

  root 'welcome#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/associate.rb
require './app/services/associate'

class Associate < ApplicationRecord
  has_many :incomes
  has_many :spendings
  has_many :salaries

  class << self
    def from_omniauth(auth_hash)
      first_associate = all.size == 0
      find_or_create_by(oauth_uid: auth_hash['uid'], oauth_provider: auth_hash['provider']) do |associate|
        # The first one to connect gets access
        # The following need to get the access from someone else
        if first_associate then
          associate.access = true
        end
        associate.display_name = auth_hash['info']['name']
        associate.email = auth_hash['info']['email']
        associate.save!
      end
    end
  end

  def data_by_month
    AssociateService.data_by_month(self)
  end

  def summary
    AssociateSummary.new(self.incomes, self.salaries, self.spendings)
  end
end

app/controllers/associates_controller.rb
class AssociatesController < ApplicationController
    before_action :set_associate, only: [:show, :edit, :update, :destroy]

    def show
        @associate = Associate.find(params[:id])
        @summary = @associate.summary
    end

    def index
        @associate = Associate.all
    end


    def new
        @associate = Associate.new
    end

    def create
        @associate = Associate.new(associate_params)

        @associate.save
        redirect_to @associate
    end

    def edit
    end

    def update
        if @associate.update(associate_params)
            redirect_to @associate, notice: 'Associé·e mis à jour.'
        else
            render :edit
        end
    end

    private

    def set_associate
        @associate = Associate.find(params[:id])
    end

    def associate_params
        params.require(:associate).permit(:display_name, :email, :access)
    end
end

app/helpers/associates_helper.rb
module AssociatesHelper
end

app/views/associates/_form.html.erb
<%= form_with(model: associate, local: true) do |form| %>
  <% if associate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(associate.errors.count, "error") %> prohibited this associate from being saved:</h2>

      <ul>
      <% associate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
        <%= form.label :display_name, "Nom d’usage" %><br>
        <%= form.text_field :display_name %>
    </div>

    <div class="field">
        <%= form.label :email, "Adresse courriel" %><br>
        <%= form.email_field :email %>
    </div>

    <div class="field">
        <%= form.label :access, "Accès au site" %><br>
        <%= form.check_box :access %>
    </div>
    
    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/associates/edit.html.erb
<h1>Édition de l’associé·e</h1>

<%= render 'form', associate: @associate %>

<%= link_to 'Voir', @associate %> |
<%= link_to 'Retour', associate_path %>

app/views/associates/index.html.erb
<h1>Liste des associés</h1>
 
<ul>
  <% @associate.each do |associate| %>
    <li>
      <%= link_to associate.display_name, associate_path(associate) %>
        <%= associate.email %>
        <% if associate.access %>(accès autorisé)<% end %>
        | <%= link_to "Modifier", edit_associate_path(associate) %>
      </li>
  <% end %>
</ul>

<p><%= link_to 'Ajouter un associé', new_associate_path %></p>

app/views/associates/new.html.erb
<h1>Ajout d’associé</h1>
<p>Attention : le compte est habituellement créé par l’associé·e directement.</p>
<p>Tout compte créé dans ce menu ne permettra pas de se connecter.</p>

<%= render 'form', associate: @associate %>

<%= link_to 'Retour', associates_path %>

app/views/associates/show.html.erb
<% if flash.notice %>
  <p id="notice"><%= notice %></p>
<% end %>
<% if flash.alert %>
  <p id="alert"><%= flash.alert %></p>
<% end %>

<div>
  <p>
    Bonjour <strong><%= @associate.display_name %></strong>
  </p>
  <ul>
    <li><strong>Bilan</string> <%= @summary.net_balance %></li>
    <li><strong>Prime proposée</string> <%= @summary.suggested_bonus %></li>
  </ul>
</div>

<%= form_for @associate.spendings.new, remote: true do |f| %>
  <%= f.hidden_field :associate_id, value: @associate.id %>
  <div class="field">
    <%= f.label :amount, "Montant" %>
    <%= f.number_field :amount, min: 0%>
    <%= select_month(Date.today, field_name: :month, prefix: :spending) %>
    <%= select_year(Date.today, field_name: :year, prefix: :spending) %>
    <%= f.submit 'Ajouter la dépense'%>
  </div>
<% end %>

<%= form_for @associate.incomes.new do |f| %>
  <%= f.hidden_field :associate_id, value: @associate.id %>
  <div class="field">
    <%= f.label :amount, "Revenu (Hors TVA)" %>
    <%= f.number_field :amount, min: 0 %>
    <%= f.label :label, "Étiquette" %>
    <%= f.text_field :label %>
    <%= select_month(Date.today, field_name: :month, prefix: :income) %>
    <%= select_year(Date.today, field_name: :year, prefix: :income) %>
    <%= f.collection_select :share_model, ShareModel.all, :id, :label %>
    <%= f.submit 'Ajouter le revenu' %>
  </div>
<% end %>

<%= form_for @associate.salaries.new do |f| %>
  <%= f.hidden_field :associate_id, value: @associate.id %>
  <div class="field">
    <%= f.label :net_pay, "Salaire net" %> <%= f.number_field :net_pay, min: 0 %>
    <%= f.label :employee_contribution, "Cotisation salariale" %> <%= f.number_field :employee_contribution, min: 0 %>
    <%= f.label :employer_contribution, "Cotisation patronale" %> <%= f.number_field :employer_contribution, min: 0 %>
    <%= f.label :saving_plan_contribution, "Abondement" %> <%= f.number_field :saving_plan_contribution, min: 0 %>
    <%= select_month(Date.today, field_name: :month, prefix: :salary) %>
    <%= select_year(Date.today, field_name: :year, prefix: :salary) %>
    <%= f.submit 'Ajouter le salaire' %>
  </div>
<% end %>

<% @associate.data_by_month.each do |month, data| %>
  <h2><%= month[1] %> / <%= month[0] %></h2>
  <% if data[:spending] %>
    <h3> Dépenses </h3>
    <ul>
      <% data[:spending].each do |spending| %>
        <li>
          <%= spending.pretty_print %>
          <%= link_to 'Supprimer', spending, method: :delete, data: { confirm: 'Êtes-vous sûr ?' } %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <% if data[:income] %>
    <h3> Revenus </h3>
    <ul>
      <% data[:income].each do |income| %>
        <li>
          <%= income.pretty_print %>
          <%= link_to 'Supprimer', income, method: :delete, data: { confirm: 'Êtes-vous sûr ?' } %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <% if data[:salary] %>
    <h3> Salaires </h3>
    <ul>
      <% data[:salary].each do |salary| %>
        <li>
          <%= salary.pretty_print %>
          <%= link_to 'Supprimer', salary, method: :delete, data: { confirm: 'Êtes-vous sûr ?' } %>
        </li>
      <% end %>
    </ul>
  <% end %>
<% end %>

<%= link_to 'Modifier', edit_associate_path(@associate) %> |
<%= link_to 'Retour', associates_path %>